name: unna
description: A social network for everyone.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  get: ^4.6.5
  firebase_auth: ^6.0.0
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  cached_network_image: ^3.2.3
  flutter_keyboard_visibility: ^6.0.0
  path_provider: ^2.0.14
  image_cropper: ^9.1.0
  image_picker: ^1.1.2
  url_launcher: ^6.1.10
  intl: ^0.20.2
  lottie: ^3.3.1
  english_words: ^4.0.0
  story: ^1.1.0  
  permission_handler_android: ^13.0.1
  quds_popup_menu: ^0.0.1+1
  scroll_date_picker: ^3.7.3

dependency_overrides: 
  agora_rtm: ^2.2.1
  iris_method_channel: ^2.2.2  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/

  fonts:
    - family: GrandHotel
      fonts:
        - asset: assets/fonts/GrandHotel-Regular.ttf
